### ISSUE TITLE
[BUG] Alert Box not showing under IE 11

### ISSUE THREAD

**Issue by pocketcap** [formio/formio.js#3462]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.12.0
- Frontend framework: vanilla JS
- Browser: IE
- Browser version: 11

## Steps to Reproduce
1. Leave required fields as empty
2. Click submit

## Expected behavior
Alert box would be shown on the top under IE 11.

## Observed behavior
Alert box is not shown on the top under IE 11. It's working fine in Chrome and Edge.

**Comment by wag110894** [comment]
Hello @pocketcap, We are aware of this issue, and has been resolved in 4.12.1-rc.16.

**Comment by pocketcap** [comment]
> Hello @pocketcap, We are aware of this issue, and has been resolved in 4.12.1-rc.16.

thanks for reply. Would it be released soon?

**Comment by pocketcap** [comment]
@wag110894 I did apply 4.12.1, and alert box started to work under IE 11. But the error message in the alert box cannot be associated to the field, which was working before. Are you aware of this?

Thanks.

**Comment by wag110894** [comment]
Hello @pocketcap, can you try upgrading to 4.12.2-rc.5? We are not experiencing this issue on the latest.

**Comment by pocketcap** [comment]
@wag110894 
I did upgrade to 4.12.2-rc.5, and am still experiencing it.

**Comment by wag110894** [comment]
Can you provide what version of the server that you are running on?

**Comment by pocketcap** [comment]
@wag110894 I am not using your server, only the Formio.js is used.

**Comment by travist** [comment]
Please provide a live example so that we can reproduce on our end. We are not successful reproducing this so there must be some other configuration you are using to not make this work.

**Comment by pocketcap** [comment]
@travist please check it out: https://jsfiddle.net/yahuiwang/ezp34Ltm/3/
You can click "Submit" at the bottom, and get validation errors. Clicking the errors won't direct you to the fields.

**Comment by wag110894** [comment]
Thank you for providing the form that you are experiencing this issue. The reason to why it was not working is because your API's contain periods (.), which is causing the issue. Once I change the API to not include the period, this is working correctly.

I hope that this helps.

**Comment by wag110894** [comment]
Hello @pocketcap,

We have created a ticket in order for this functionality to work when periods included inside the API property.  For reference, the ticket number is FIO-1016. We welcome a pull request. We also do have a process to expedite if you are interested. Please let me know if you are interested and we can get the process started.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
