### ISSUE TITLE
Dynamic Select Filtering in editGrid and dataGrid

### ISSUE THREAD

**Issue by Eric4565** [formio/formio.js#524]
When I want to add a data with the add button in a datagrid or an editgrid , the dynamic select filtering doesn't work from the second data entered. The reason is that after choosing a value in the first select component, I got the console error: "ERROR TypeError: Cannot set property 'selected' of undefined".

When Im using the same Dynamic select filtering outside a datagrid  or editgrid everything works fine as well as the first data selected the first time in grids.

**Comment by peterjohnbull** [comment]
Same for me, too.

**Comment by jhen1422** [comment]
This issue has been resolved

**Comment by MasallahOZEN** [comment]
Hi, can you doing Dynamic Select Filtering ? How can I do that?

**Comment by jhen1422** [comment]
Hello @MasallahOZEN ,

Please review our help documentation on how to implement dynamic select filtering 
https://help.form.io/tutorials/walkthroughs/dynamic-select-filtering/

Please keep in mind to use 'row' instead of the 'data' attribute when using Edit Grids / Data Grids

**Comment by jnewman30** [comment]
This still doesn't work... Even in the example in the link above on your page:
https://help.form.io/tutorials/walkthroughs/dynamic-select-filtering/

**Comment by wag110894** [comment]
Hello @jnewman30,

Apologies that the example is not currently working. We will work on getting that fixed. In the meantime, here is an example of dynamic-select-filtering working: https://jsfiddle.net/g3Lzh21x/. 
You can also download the project schema at the link you mentioned above and follow the documentation and see that it does work.
