### ISSUE TITLE
[Bug] Form Builder - cannot remove column in columns component

### ISSUE THREAD

**Issue by Davidvlv** [formio/formio.js#552]
Hi, I have found a bug in the Form Builder in 3.0.0-rc.XX:

You can add extra columns to the columns component, but when you press the [x] to remove a column and then click save, it does not remove the column.

![image](https://user-images.githubusercontent.com/24515980/42549986-5b197652-8512-11e8-858f-eeb2a6775af5.png)

**Comment by ensemblebd** [comment]
EditComponent event confirms prior to clone that data is unaffected by the button to remove. 
So that leads us to DataGrid, as per `src\components\columns\editForm\Columns.edit.display.js`

The event is propagated up to the Base.js -> removeChildFrom.
All it does is process each of the 4 "components" (elements in columns in the row for the intended row to delete). 
So, without digging deeper than that, and after running grep scan for keyword "delete" and "remove", I would like to say that the even is completely unhandled, and doesn't alter the internal data of the column whatsoever. 
I could be wrong, but not seeing it.

**Comment by jhen1422** [comment]
This issue has been resolved

**Comment by AvnishVerma** [comment]
Hi 
I am facing same issue, If I added new Column in columns component and then I save it. now I edit columns and remove newly added column and save it. Still it that column exist on canvas. And when I click on edit it still shows three rows in grid.

**Comment by wag110894** [comment]
Thank you for reaching out!
We have created a ticket (FOR-2172) and have added this to our planning document to be discussed in our planning session on Monday.

We will let you know the priority level of this item then.

Thanks!

**Comment by ranjanitechleaf** [comment]
Is this issue fixed?  Have any solution ?
please help us

**Comment by wag110894** [comment]
This item is currently on one of our Developers List. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.

Thanks.

**Comment by jhen1422** [comment]
@Davidvlv @ssrini  Can you please confirm if this is still an issue for you on the latest builder/renderer versions? Unable to replicate on our end.

**Comment by srinisubramanian** [comment]
@jhen1422 Still an issue, I updated #1422  with sample
